In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
movies = pd.read_csv("tmdb_top_10k_movies_2026.csv.csv")

In [7]:
movies.head()

,Unnamed: 0,genre_ids,id,original_language,overview,popularity,release_date,title,vote_average,vote_count
0,0,"[18, 80]",278,en,Imprisoned in the 1940s for the double murder ...,30.8191,1994-09-23,The Shawshank Redemption,8.716,29721
1,1,"[18, 80]",238,en,"Spanning the years 1945 to 1955, a chronicle o...",36.4215,1972-03-14,The Godfather,8.687,22451
2,2,"[18, 80]",240,en,In the continuing saga of the Corleone crime f...,17.5941,1974-12-20,The Godfather Part II,8.571,13586
3,3,"[18, 36, 10752]",424,en,The true story of how businessman Oskar Schind...,18.6937,1993-12-15,Schindler's List,8.567,17106
4,4,[18],389,en,The defense and the prosecution have rested an...,13.0084,1957-04-10,12 Angry Men,8.555,9741

In [8]:
movies.shape

(10000, 10)

In [9]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         10000 non-null  int64
 1   genre_ids          10000 non-null  object
 2   id                 10000 non-null  int64
 3   original_language  10000 non-null  object
 4   overview           9998 non-null   object
 5   popularity         10000 non-null  float64
 6   release_date       9997 non-null   object
 7   title              10000 non-null  object
 8   vote_average       10000 non-null  float64
 9   vote_count         10000 non-null  int64
dtypes: float64(2), int64(3), object(5)
memory usage: 781.4+ KB

In [10]:
movies.describe()

        Unnamed: 0            id    popularity  vote_average    vote_count
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000
mean    4999.50000  2.252508e+05      4.280559      6.729167   2077.979600
std     2886.89568  2.991634e+05      7.960604      0.660076   3318.455958
min        0.00000  2.000000e+00      0.003200      5.400000    300.000000
25%     2499.75000  1.032975e+04      1.776575      6.212750    473.000000
50%     4999.50000  4.162000e+04      2.855200      6.700000    868.000000
75%     7499.25000  4.033328e+05      4.874800      7.208000   2077.250000
max     9999.00000  1.472638e+06    340.838100      8.716000  38859.000000

In [11]:
movies.isnull().sum().sort_values(ascending=False)

release_date         3
overview             2
genre_ids            0
Unnamed: 0           0
original_language    0
id                   0
popularity           0
title                0
vote_average         0
vote_count           0
dtype: int64

In [12]:
movies.columns

Index(['Unnamed: 0', 'genre_ids', 'id', 'original_language', 'overview',
       'popularity', 'release_date', 'title', 'vote_average', 'vote_count'],
      dtype='object')

In [13]:
movies=movies[['genre_ids','id','overview','title']]
movies

,genre_ids,id,overview,title
0,"[18, 80]",278,Imprisoned in the 1940s for the double murder ...,The Shawshank Redemption
1,"[18, 80]",238,"Spanning the years 1945 to 1955, a chronicle o...",The Godfather
2,"[18, 80]",240,In the continuing saga of the Corleone crime f...,The Godfather Part II
3,"[18, 36, 10752]",424,The true story of how businessman Oskar Schind...,Schindler's List
4,[18],389,The defense and the prosecution have rested an...,12 Angry Men
...,...,...,...,...
9995,"[27, 35]",10012,A werewolf loose in Los Angeles changes the li...,Cursed
9996,"[28, 53, 80]",480042,After security expert Ray Breslin is hired to ...,Escape Plan: The Extractors
9997,"[27, 9648]",465086,After a young mother murders her family in her...,The Grudge
9998,"[35, 53]",276839,"Don Champagne seems to have it all, but when h...",Home Sweet Hell
9999,"[12, 10751, 35, 14]",39346,Before he met and befriended the other ghouls ...,Casper: A Spirited Beginning

In [14]:
import ast

ast.literal_eval("[18,80]")

[18, 80]

In [15]:
genre_map = {
    28: "Action",
    12: "Adventure",
    16: "Animation",
    35: "Comedy",
    80: "Crime",
    99: "Documentary",
    18: "Drama",
    10751: "Family",
    14: "Fantasy",
    36: "History",
    27: "Horror",
    10402: "Music",
    9648: "Mystery",
    10749: "Romance",
    878: "SciFi",
    10770: "TVMovie",
    53: "Thriller",
    10752: "War",
    37: "Western"
}

In [16]:
def convert_genres(x):

    ids = ast.literal_eval(x)

    names = []

    for i in ids:
        if i in genre_map:
            names.append(genre_map[i])

    return " ".join(names)

In [18]:
movies["genres"] = movies["genre_ids"].apply(convert_genres)

In [19]:
movies["Tags"] = (
    movies["genres"]
    + " " + movies["overview"]
)

In [20]:
movies

,genre_ids,id,overview,title,genres,Tags
0,"[18, 80]",278,Imprisoned in the 1940s for the double murder ...,The Shawshank Redemption,Drama Crime,Drama Crime Imprisoned in the 1940s for the do...
1,"[18, 80]",238,"Spanning the years 1945 to 1955, a chronicle o...",The Godfather,Drama Crime,"Drama Crime Spanning the years 1945 to 1955, a..."
2,"[18, 80]",240,In the continuing saga of the Corleone crime f...,The Godfather Part II,Drama Crime,Drama Crime In the continuing saga of the Corl...
3,"[18, 36, 10752]",424,The true story of how businessman Oskar Schind...,Schindler's List,Drama History War,Drama History War The true story of how busine...
4,[18],389,The defense and the prosecution have rested an...,12 Angry Men,Drama,Drama The defense and the prosecution have res...
...,...,...,...,...,...,...
9995,"[27, 35]",10012,A werewolf loose in Los Angeles changes the li...,Cursed,Horror Comedy,Horror Comedy A werewolf loose in Los Angeles ...
9996,"[28, 53, 80]",480042,After security expert Ray Breslin is hired to ...,Escape Plan: The Extractors,Action Thriller Crime,Action Thriller Crime After security expert Ra...
9997,"[27, 9648]",465086,After a young mother murders her family in her...,The Grudge,Horror Mystery,Horror Mystery After a young mother murders he...
9998,"[35, 53]",276839,"Don Champagne seems to have it all, but when h...",Home Sweet Hell,Comedy Thriller,Comedy Thriller Don Champagne seems to have it...
9999,"[12, 10751, 35, 14]",39346,Before he met and befriended the other ghouls ...,Casper: A Spirited Beginning,Adventure Family Comedy Fantasy,Adventure Family Comedy Fantasy Before he met ...

In [21]:
new_data=movies.drop(columns=['overview','genres'])

In [22]:
new_data

,genre_ids,id,title,Tags
0,"[18, 80]",278,The Shawshank Redemption,Drama Crime Imprisoned in the 1940s for the do...
1,"[18, 80]",238,The Godfather,"Drama Crime Spanning the years 1945 to 1955, a..."
2,"[18, 80]",240,The Godfather Part II,Drama Crime In the continuing saga of the Corl...
3,"[18, 36, 10752]",424,Schindler's List,Drama History War The true story of how busine...
4,[18],389,12 Angry Men,Drama The defense and the prosecution have res...
...,...,...,...,...
9995,"[27, 35]",10012,Cursed,Horror Comedy A werewolf loose in Los Angeles ...
9996,"[28, 53, 80]",480042,Escape Plan: The Extractors,Action Thriller Crime After security expert Ra...
9997,"[27, 9648]",465086,The Grudge,Horror Mystery After a young mother murders he...
9998,"[35, 53]",276839,Home Sweet Hell,Comedy Thriller Don Champagne seems to have it...
9999,"[12, 10751, 35, 14]",39346,Casper: A Spirited Beginning,Adventure Family Comedy Fantasy Before he met ...

In [23]:
movies.duplicated().sum()

np.int64(35)

In [24]:
movies.drop_duplicates(inplace=True)

In [25]:
movies.shape

(9965, 6)

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

In [27]:
cv= CountVectorizer(max_features=10000,stop_words='english')

In [28]:
vector= cv.fit_transform(new_data['Tags'].values.astype('U')).toarray()

In [29]:
vector.shape

(10000, 10000)

In [30]:
from sklearn.metrics.pairwise import cosine_similarity

In [31]:
similarity= cosine_similarity(vector)
similarity

array([[1.        , 0.12858612, 0.11433239, ..., 0.        , 0.13867505,
        0.        ],
       [0.12858612, 1.        , 0.47633051, ..., 0.11268723, 0.04279605,
        0.06052275],
       [0.11433239, 0.47633051, 1.        , ..., 0.18786729, 0.04756515,
        0.10090092],
       ...,
       [0.        , 0.11268723, 0.18786729, ..., 1.        , 0.        ,
        0.17902872],
       [0.13867505, 0.04279605, 0.04756515, ..., 0.        , 1.        ,
        0.05439283],
       [0.        , 0.06052275, 0.10090092, ..., 0.17902872, 0.05439283,
        1.        ]], shape=(10000, 10000))

In [32]:
new_data[new_data['title']=='The Godfather'].index[0]

np.int64(1)

In [33]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   genre_ids  10000 non-null  object
 1   id         10000 non-null  int64
 2   title      10000 non-null  object
 3   Tags       9998 non-null   object
dtypes: int64(1), object(3)
memory usage: 312.6+ KB

In [34]:
distance=sorted(list(enumerate(similarity[1])),reverse=True,key=lambda x:x[1])
for i in distance[0:6]:
  print(new_data.iloc[i[0]].title)

The Godfather
The Godfather Part II
Blood Ties
Joker
Felon
Batman: The Killing Joke

In [35]:
def recommend(movies):
  index=new_data[new_data['title']==movies].index[0]
  distance=sorted(list(enumerate(similarity[index])),reverse=True,key=lambda x:x[1])
  for i in distance[0:5]:
    print(new_data.iloc[i[0]].title)

In [39]:
recommend("Iron Man")

Iron Man
Iron Man 3
Avengers: Age of Ultron
Iron Man 2
Guardians of the Galaxy Vol. 2

In [37]:
import pickle

In [38]:
pickle.dump(new_data,open('movies_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

In [ ]:
pickle.load(open('movies_list.pkl','rb'))

,genre_ids,id,title,Tags
0,"[18, 80]",278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...
1,"[18, 80]",238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
2,"[18, 80]",240,The Godfather Part II,In the continuing saga of the Corleone crime f...
3,"[18, 36, 10752]",424,Schindler's List,The true story of how businessman Oskar Schind...
4,[18],389,12 Angry Men,The defense and the prosecution have rested an...
...,...,...,...,...
9995,"[27, 35]",10012,Cursed,A werewolf loose in Los Angeles changes the li...
9996,"[28, 53, 80]",480042,Escape Plan: The Extractors,After security expert Ray Breslin is hired to ...
9997,"[27, 9648]",465086,The Grudge,After a young mother murders her family in her...
9998,"[35, 53]",276839,Home Sweet Hell,"Don Champagne seems to have it all, but when h..."
9999,"[12, 10751, 35, 14]",39346,Casper: A Spirited Beginning,Before he met and befriended the other ghouls ...